// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.huy.myfinance.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Single buffered notification item passed from native to Dart.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RawCaptureMessage (
  /** Stable UUID assigned by the native buffer on arrival. */
  val id: String,
  /** Android package name of the notification source app. */
  val packageName: String,
  /** Notification title — null when the notification has no title. */
  val title: String? = null,
  /** Notification body text (EXTRA_BIG_TEXT preferred, EXTRA_TEXT fallback). */
  val text: String,
  /** [notificationInfo.postTime] in milliseconds since epoch. */
  val postTimeMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RawCaptureMessage {
      val id = pigeonVar_list[0] as String
      val packageName = pigeonVar_list[1] as String
      val title = pigeonVar_list[2] as String?
      val text = pigeonVar_list[3] as String
      val postTimeMillis = pigeonVar_list[4] as Long
      return RawCaptureMessage(id, packageName, title, text, postTimeMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      packageName,
      title,
      text,
      postTimeMillis,
    )
  }
}
private open class CaptureChannelPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RawCaptureMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is RawCaptureMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Dart → native channel. Dart pulls; native never pushes.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface CaptureHostApi {
  /**
   * Persists [packages] as the set of packages whose notifications are
   * buffered. Replaces any previous set. Called on every drain so the watch
   * list stays in sync even after wallets are added.
   */
  fun setWatchedPackages(packages: List<String>)
  /**
   * Returns all buffered captures without clearing the buffer.
   * Call [clearCaptures] with their ids after Dart has filed them.
   */
  fun drainCaptures(): List<RawCaptureMessage>
  /**
   * Removes the captures identified by [ids] from the native buffer.
   * Removes by id — never blanket-overwrites — so captures that arrived
   * during the drain window are preserved.
   */
  fun clearCaptures(ids: List<String>)
  /**
   * Returns the set of package names that have posted at least one
   * notification since the last app install. Names only — no content.
   * Used by the discovery surface to identify real bank package names.
   */
  fun seenPackages(): List<String>
  /**
   * Returns true if this app's [NotificationListenerService] is in the
   * system-enabled listeners list.
   */
  fun isListenerEnabled(): Boolean
  /**
   * Deep-links to the notification listener settings screen so the user can
   * grant or revoke access. Does not show a runtime permission dialog.
   */
  fun openListenerSettings()

  companion object {
    /** The codec used by CaptureHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CaptureChannelPigeonCodec()
    }
    /** Sets up an instance of `CaptureHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CaptureHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.myfinance.CaptureHostApi.setWatchedPackages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packagesArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              api.setWatchedPackages(packagesArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.myfinance.CaptureHostApi.drainCaptures$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.drainCaptures())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.myfinance.CaptureHostApi.clearCaptures$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idsArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              api.clearCaptures(idsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.myfinance.CaptureHostApi.seenPackages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.seenPackages())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.myfinance.CaptureHostApi.isListenerEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isListenerEnabled())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.myfinance.CaptureHostApi.openListenerSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openListenerSettings()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
